services:
  dyma-postgresql:
    image: postgres:17
    container_name: escanor-postgres-production
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=5ML^Es#x%4U&DK6c
    ports:
      - '5424:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data


# docker compose -f src/main/docker/prod/postgresql.yml up
# docker compose -f src/main/docker/prod/postgresql.yml down

# docker exec -it dyma-postgres-production bash
# psql -U postgres

# ./mvnw clean spring-boot:run \
# -Dspring-boot.run.profiles=prod \
# -Dspring-boot.run.arguments="--spring.datasource.url=jdbc:postgresql://localhost:5424/postgres --spring.datasource.username=postgres --spring.datasource.password=5ML^Es#x%4U&DK6c"
